#!/usr/bin/env bash

# Creates a PR using hub's `pull-request` command against whatever release branch the current
# branch spawned from

set -e

BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [ "$BRANCH" == "master" ]; then
  hub pull-request
else
  TARGET=$(git branch --merged $BRANCH | grep -E "^  release/[0-9]*\.[0-9]*\$" | xargs)
  echo "Making PR against $TARGET"
  sleep 1
  hub pull-request -b "$TARGET"
fi
