#!/usr/bin/env bash
set -e

cd $(git rev-parse --show-toplevel)

if [ -e *.cabal ]; then
    # Hasktags for Haskell
    CT="hasktags -c --ignore-close-implementation -o .git/tags.$$ -R ."
elif [ -e *.sbt ]; then
    # stags for Scala
    CT="stags -d 2 -o .git/tags.$$ ."
else
    # For everything else, ctags. Make sure to generate absolute tag paths.
    CT="ctags --tag-relative=always --sort=foldcase -Rf.git/tags.$$ --exclude=.git --languages=-XML,javascript,sql,html,Iniconf,CSS,JSON,SVG,C++,Make,JavaProperties,Diff,Java $(pwd)"
fi

trap "rm -f .git/tags.$$" EXIT
eval "$CT"
mv .git/tags.$$ .git/tags
