#!/bin/sh
set -e

if [ -e *.cabal ]; then
    # Hasktags for Haskell
    CT="hasktags -c -o .git/tags.$$ -R ."
else
    # For everything else, ctags
    CT="ctags --tag-relative -Rf.git/tags.$$ --exclude=.git --languages=-javascript,sql"
fi

PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT
eval "$CT"
mv .git/tags.$$ .git/tags
