#!/usr/bin/env fish

set lang (git config --local project.language)

switch (echo $lang)
  case scala
    scalafmt --diff-branch HEAD --test --quiet
  case ''
    echo "No project.language set for project. Set one with git config --local project.language <language>"
  case '*'
    echo "No formatter for $lang"
end

git diff --cached --name-only | not xargs grep -E "TODO (\(?NOW\)?|\(?XXX\)?)"
